version: "3.8"
services:
    backend:
        env_file: 
            - .env
        environment:
            - DJANGO_SETTINGS_MODULE=mysite.settings.dev
        build: 
            context: ./
            dockerfile: Dockerfile
        image: wagtail-gatsby-blog-backend
        # command: Not needed. Already defined in Dockerfile
        restart: "no"  # probably not in development
        ports: 
            - "127.0.0.1:8000:8000"
        volumes:
            - ./:/code/

