version: "3.8"
services:
    wagtail:
        environment:
            - DJANGO_SETTINGS_MODULE=mysite.settings.dev
        build: 
            context: ./
            dockerfile: Dockerfile
        image: wagtail-gatsby-blog-wagtail:dev
        # command: Not needed. Already defined in Dockerfile
        restart: "no"  # probably not in development
        ports: 
            - "127.0.0.1:8080:8000"
        volumes:
            - ./:/code/

