version: "3.8"
services:
    wagtail:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: wagtail-gatsby-blog-wagtail:production
        container_name: wagtail-gatsby-blog-wagtail
        env_file:
            - .env
        # command: Not needed. Already defined in Dockerfile
        restart: unless-stopped
        ports: 
            - "127.0.0.1:8101:8000"
        volumes:
            - appdata:/code/data
        networks:
            - appnet
    nginx:
        build:
            context: ./container/nginx
        image: wagtail-gatsby-blog-nginx:production
        container_name: wagtail-gatsby-blog-nginx
        depends_on:
            - wagtail
        restart: unless-stopped
        ports: 
            - "127.0.0.1:8102:80"
        volumes:
            - appdata:/code/data:ro
        networks:
            - appnet

volumes:
    appdata:
        name: wagtail-gatsby-blog-data

networks:
    appnet:
        name: wagtail-gatsby-blog-network