version: "3.8"
services:
    backend:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: wagtail-gatsby-blog-backend
        # command: Not needed. Already defined in Dockerfile
        restart: unless-stopped
        ports: 
            - "127.0.0.1:8000:8000"
        volumes:
            - ./data:/code/data

