version: "3.8"
services:
    backend:
        build: 
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
        image: wagtail-gatsby-blog-backend
        # command: Not needed. Already defined in Dockerfile
        restart: unless-stopped
        ports: 
            - "127.0.0.1:8000:8000"
        volumes:
            - appdata:/code/data
    static:
        build:
            context: ./container/nginx
        depends_on:
            - backend
        image: wagtail-gatsby-blog-nginx
        restart: unless-stopped
        ports: 
            - "127.0.0.1:9000:80"
        volumes:
            - appdata:/code/data

volumes:
    appdata: