# Generated by Django 2.2.13 on 2020-06-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200618_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='content_object',
            new_name='tagged_blog_page',
        ),
    ]
