# Generated by Django 2.2.13 on 2020-06-24 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='icom',
            new_name='icon',
        ),
    ]
