name: Update production server
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Docker Images (Build and Push)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wagtail image (build and push)
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-wagtail
          tags: latest, production
          path: .
          dockerfile: ./docker/wagtail/Dockerfile
          cache_froms: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-wagtail:latest

      - name: Nginx image (build and push)
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-nginx
          tags: latest, production
          path: ./docker/nginx
          dockerfile: ./docker/nginx/Dockerfile
          cache_froms: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-nginx:latest

  update:
    name: Update Production Server
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup ssh configuration
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent -s) 
          ssh-keyscan -p 22 -t rsa ${{secrets.REMOTE_HOST}} 
          echo "${{secrets.REMOTE_KNOWN_HOST}}" > ~/.ssh/known_hosts 
          chmod -R 700 ~/.ssh
          ssh-add <(echo "${{secrets.SSH_PRIVATE_KEY}}") 

      - name: Download new images
        run: ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa docker-compose -f ${{secrets.REMOTE_HOST_PROJECT_DIR}}/docker-compose.yml pull

      - name: Teardown running containers
        run: ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa docker-compose -f ${{secrets.REMOTE_HOST_PROJECT_DIR}}/docker-compose.yml down

      - name: Start new containers
        run: ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa docker-compose -f ${{secrets.REMOTE_HOST_PROJECT_DIR}}/docker-compose.yml up -d

      - name: Remove ssh configutation
        run: |
          ssh-agent -k
          rm -rf ~/.ssh