name: Build and push production Docker images
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push wagtail image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-wagtail
          tags: latest, production
          path: .
          dockerfile: ./docker/wagtail/Dockerfile
