name: Build and push production Docker images
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push wagtail image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-wagtail
          tags: latest, production
          path: .
          dockerfile: ./docker/wagtail/Dockerfile
          cache_froms: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-wagtail:latest

      - name: Build and push nginx image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-nginx
          tags: latest, production
          path: ./docker/nginx
          dockerfile: ./docker/nginx/Dockerfile
          cache_froms: ${{ secrets.DOCKER_USERNAME }}/wagtail-gatsby-blog-nginx:latest

      - name: Update running container on remote host
        run: |
          ssh-keyscan -p 22 -t rsa ${{secrets.REMOTE_HOST}} 
          mkdir -p ~/.ssh
          echo "${{secrets.REMOTE_KNOWN_HOST}}" > ~/.ssh/known_hosts 
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod -R 700 ~/.ssh
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
          ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa docker-compose -f {{secrets.REMOTE_HOST_PROJECT_DIR}}/docker-compose.yml pull
          ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa docker-compose -f {{secrets.REMOTE_HOST_PROJECT_DIR}}/docker-compose.yml down
          ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa docker-compose -f {{secrets.REMOTE_HOST_PROJECT_DIR}}/docker-compose.yml up
          rm -rf ~/.ssh